/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for CreateDatasetItemRequest
 */
public class CreateDatasetItemRequestTest {
    private final CreateDatasetItemRequest model = new CreateDatasetItemRequest();

    /**
     * Model tests for CreateDatasetItemRequest
     */
    @Test
    public void testCreateDatasetItemRequest() {
        // TODO: test CreateDatasetItemRequest
    }

    /**
     * Test the property 'datasetName'
     */
    @Test
    public void datasetNameTest() {
        // TODO: test datasetName
    }

    /**
     * Test the property 'input'
     */
    @Test
    public void inputTest() {
        // TODO: test input
    }

    /**
     * Test the property 'expectedOutput'
     */
    @Test
    public void expectedOutputTest() {
        // TODO: test expectedOutput
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

}
