/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DatasetRunItem
 */
public class DatasetRunItemTest {
    private final DatasetRunItem model = new DatasetRunItem();

    /**
     * Model tests for DatasetRunItem
     */
    @Test
    public void testDatasetRunItem() {
        // TODO: test DatasetRunItem
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'datasetRunId'
     */
    @Test
    public void datasetRunIdTest() {
        // TODO: test datasetRunId
    }

    /**
     * Test the property 'datasetItemId'
     */
    @Test
    public void datasetItemIdTest() {
        // TODO: test datasetItemId
    }

    /**
     * Test the property 'observationId'
     */
    @Test
    public void observationIdTest() {
        // TODO: test observationId
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

}
