/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for IngestionBatchRequest
 */
public class IngestionBatchRequestTest {
    private final IngestionBatchRequest model = new IngestionBatchRequest();

    /**
     * Model tests for IngestionBatchRequest
     */
    @Test
    public void testIngestionBatchRequest() {
        // TODO: test IngestionBatchRequest
    }

    /**
     * Test the property 'batch'
     */
    @Test
    public void batchTest() {
        // TODO: test batch
    }

}
