/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OpenAIUsage
 */
public class OpenAIUsageTest {
    private final OpenAIUsage model = new OpenAIUsage();

    /**
     * Model tests for OpenAIUsage
     */
    @Test
    public void testOpenAIUsage() {
        // TODO: test OpenAIUsage
    }

    /**
     * Test the property 'promptTokens'
     */
    @Test
    public void promptTokensTest() {
        // TODO: test promptTokens
    }

    /**
     * Test the property 'completionTokens'
     */
    @Test
    public void completionTokensTest() {
        // TODO: test completionTokens
    }

    /**
     * Test the property 'totalTokens'
     */
    @Test
    public void totalTokensTest() {
        // TODO: test totalTokens
    }

}
