/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DatasetRunItem
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DatasetRunItem {
  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_DATASET_RUN_ID = "datasetRunId";
  @SerializedName(SERIALIZED_NAME_DATASET_RUN_ID)
  private String datasetRunId;

  public static final String SERIALIZED_NAME_DATASET_ITEM_ID = "datasetItemId";
  @SerializedName(SERIALIZED_NAME_DATASET_ITEM_ID)
  private String datasetItemId;

  public static final String SERIALIZED_NAME_OBSERVATION_ID = "observationId";
  @SerializedName(SERIALIZED_NAME_OBSERVATION_ID)
  private String observationId;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  private OffsetDateTime updatedAt;

  public DatasetRunItem() {
  }

  public DatasetRunItem id(String id) {
    
    
    
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    
    
    
    this.id = id;
  }


  public DatasetRunItem datasetRunId(String datasetRunId) {
    
    
    
    
    this.datasetRunId = datasetRunId;
    return this;
  }

   /**
   * Get datasetRunId
   * @return datasetRunId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getDatasetRunId() {
    return datasetRunId;
  }


  public void setDatasetRunId(String datasetRunId) {
    
    
    
    this.datasetRunId = datasetRunId;
  }


  public DatasetRunItem datasetItemId(String datasetItemId) {
    
    
    
    
    this.datasetItemId = datasetItemId;
    return this;
  }

   /**
   * Get datasetItemId
   * @return datasetItemId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getDatasetItemId() {
    return datasetItemId;
  }


  public void setDatasetItemId(String datasetItemId) {
    
    
    
    this.datasetItemId = datasetItemId;
  }


  public DatasetRunItem observationId(String observationId) {
    
    
    
    
    this.observationId = observationId;
    return this;
  }

   /**
   * Get observationId
   * @return observationId
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public String getObservationId() {
    return observationId;
  }


  public void setObservationId(String observationId) {
    
    
    
    this.observationId = observationId;
  }


  public DatasetRunItem createdAt(OffsetDateTime createdAt) {
    
    
    
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    
    
    
    this.createdAt = createdAt;
  }


  public DatasetRunItem updatedAt(OffsetDateTime updatedAt) {
    
    
    
    
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }


  public void setUpdatedAt(OffsetDateTime updatedAt) {
    
    
    
    this.updatedAt = updatedAt;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DatasetRunItem instance itself
   */
  public DatasetRunItem putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DatasetRunItem datasetRunItem = (DatasetRunItem) o;
    return Objects.equals(this.id, datasetRunItem.id) &&
        Objects.equals(this.datasetRunId, datasetRunItem.datasetRunId) &&
        Objects.equals(this.datasetItemId, datasetRunItem.datasetItemId) &&
        Objects.equals(this.observationId, datasetRunItem.observationId) &&
        Objects.equals(this.createdAt, datasetRunItem.createdAt) &&
        Objects.equals(this.updatedAt, datasetRunItem.updatedAt)&&
        Objects.equals(this.additionalProperties, datasetRunItem.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, datasetRunId, datasetItemId, observationId, createdAt, updatedAt, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DatasetRunItem {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    datasetRunId: ").append(toIndentedString(datasetRunId)).append("\n");
    sb.append("    datasetItemId: ").append(toIndentedString(datasetItemId)).append("\n");
    sb.append("    observationId: ").append(toIndentedString(observationId)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("id");
    openapiFields.add("datasetRunId");
    openapiFields.add("datasetItemId");
    openapiFields.add("observationId");
    openapiFields.add("createdAt");
    openapiFields.add("updatedAt");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("id");
    openapiRequiredFields.add("datasetRunId");
    openapiRequiredFields.add("datasetItemId");
    openapiRequiredFields.add("observationId");
    openapiRequiredFields.add("createdAt");
    openapiRequiredFields.add("updatedAt");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DatasetRunItem
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DatasetRunItem.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DatasetRunItem is not found in the empty JSON string", DatasetRunItem.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DatasetRunItem.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if (!jsonObj.get("datasetRunId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `datasetRunId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("datasetRunId").toString()));
      }
      if (!jsonObj.get("datasetItemId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `datasetItemId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("datasetItemId").toString()));
      }
      if (!jsonObj.get("observationId").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `observationId` to be a primitive type in the JSON string but got `%s`", jsonObj.get("observationId").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DatasetRunItem.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DatasetRunItem' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DatasetRunItem> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DatasetRunItem.class));

       return (TypeAdapter<T>) new TypeAdapter<DatasetRunItem>() {
           @Override
           public void write(JsonWriter out, DatasetRunItem value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DatasetRunItem read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DatasetRunItem instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DatasetRunItem given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DatasetRunItem
  * @throws IOException if the JSON string is invalid with respect to DatasetRunItem
  */
  public static DatasetRunItem fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DatasetRunItem.class);
  }

 /**
  * Convert an instance of DatasetRunItem to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

