/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CreateDatasetRequest;
import com.konfigthis.client.model.Dataset;
import com.konfigthis.client.model.DatasetRun;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for DatasetsApi
 */
@Disabled
public class DatasetsApiTest {

    private static DatasetsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new DatasetsApi(apiClient);
    }

    /**
     * Create a dataset
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        String name = null;
        Dataset response = api.create(name)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a dataset and its items
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTest() throws ApiException {
        String datasetName = null;
        Dataset response = api.get(datasetName)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a dataset run and its items
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRunsTest() throws ApiException {
        String datasetName = null;
        String runName = null;
        DatasetRun response = api.getRuns(datasetName, runName)
                .execute();
        // TODO: test validations
    }

}
