/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.DailyMetrics;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MetricsApi
 */
@Disabled
public class MetricsApiTest {

    private static MetricsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new MetricsApi(apiClient);
    }

    /**
     * Get daily metrics of the Langfuse project
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void dailyTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String traceName = null;
        String userId = null;
        List<String> tags = null;
        DailyMetrics response = api.daily()
                .page(page)
                .limit(limit)
                .traceName(traceName)
                .userId(userId)
                .tags(tags)
                .execute();
        // TODO: test validations
    }

}
