/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.CreatePromptRequest;
import com.konfigthis.client.model.Prompt;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for PromptsApi
 */
@Disabled
public class PromptsApiTest {

    private static PromptsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new PromptsApi(apiClient);
    }

    /**
     * Create a prompt
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void createTest() throws ApiException {
        String name = null;
        Boolean isActive = null;
        String prompt = null;
        Object config = null;
        Prompt response = api.create(name, isActive, prompt)
                .config(config)
                .execute();
        // TODO: test validations
    }

    /**
     * Get a prompt
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTest() throws ApiException {
        String name = null;
        Integer version = null;
        Prompt response = api.get(name)
                .version(version)
                .execute();
        // TODO: test validations
    }

}
