/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Trace;
import com.konfigthis.client.model.Traces;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TraceApi
 */
@Disabled
public class TraceApiTest {

    private static TraceApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new TraceApi(apiClient);
    }

    /**
     * Get a specific trace
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getTest() throws ApiException {
        String traceId = null;
        Trace response = api.get(traceId)
                .execute();
        // TODO: test validations
    }

    /**
     * Get list of traces
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listTest() throws ApiException {
        Integer page = null;
        Integer limit = null;
        String userId = null;
        String name = null;
        String orderBy = null;
        List<String> tags = null;
        Traces response = api.list()
                .page(page)
                .limit(limit)
                .userId(userId)
                .name(name)
                .orderBy(orderBy)
                .tags(tags)
                .execute();
        // TODO: test validations
    }

}
