/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.CreateDatasetRunItemRequest;
import com.konfigthis.client.model.DatasetRunItem;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class DatasetRunItemsApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public DatasetRunItemsApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public DatasetRunItemsApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call createCall(CreateDatasetRunItemRequest createDatasetRunItemRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = createDatasetRunItemRequest;

        // create path and map variables
        String localVarPath = "/api/public/dataset-run-items";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BasicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call createValidateBeforeCall(CreateDatasetRunItemRequest createDatasetRunItemRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'createDatasetRunItemRequest' is set
        if (createDatasetRunItemRequest == null) {
            throw new ApiException("Missing the required parameter 'createDatasetRunItemRequest' when calling create(Async)");
        }

        return createCall(createDatasetRunItemRequest, _callback);

    }


    private ApiResponse<DatasetRunItem> createWithHttpInfo(CreateDatasetRunItemRequest createDatasetRunItemRequest) throws ApiException {
        okhttp3.Call localVarCall = createValidateBeforeCall(createDatasetRunItemRequest, null);
        Type localVarReturnType = new TypeToken<DatasetRunItem>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call createAsync(CreateDatasetRunItemRequest createDatasetRunItemRequest, final ApiCallback<DatasetRunItem> _callback) throws ApiException {

        okhttp3.Call localVarCall = createValidateBeforeCall(createDatasetRunItemRequest, _callback);
        Type localVarReturnType = new TypeToken<DatasetRunItem>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class CreateRequestBuilder {
        private final String runName;
        private final String datasetItemId;
        private final String observationId;

        private CreateRequestBuilder(String runName, String datasetItemId, String observationId) {
            this.runName = runName;
            this.datasetItemId = datasetItemId;
            this.observationId = observationId;
        }

        /**
         * Build call for create
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            CreateDatasetRunItemRequest createDatasetRunItemRequest = buildBodyParams();
            return createCall(createDatasetRunItemRequest, _callback);
        }

        private CreateDatasetRunItemRequest buildBodyParams() {
            CreateDatasetRunItemRequest createDatasetRunItemRequest = new CreateDatasetRunItemRequest();
            createDatasetRunItemRequest.runName(this.runName);
            createDatasetRunItemRequest.datasetItemId(this.datasetItemId);
            createDatasetRunItemRequest.observationId(this.observationId);
            return createDatasetRunItemRequest;
        }

        /**
         * Execute create request
         * @return DatasetRunItem
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public DatasetRunItem execute() throws ApiException {
            CreateDatasetRunItemRequest createDatasetRunItemRequest = buildBodyParams();
            ApiResponse<DatasetRunItem> localVarResp = createWithHttpInfo(createDatasetRunItemRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute create request with HTTP info returned
         * @return ApiResponse&lt;DatasetRunItem&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<DatasetRunItem> executeWithHttpInfo() throws ApiException {
            CreateDatasetRunItemRequest createDatasetRunItemRequest = buildBodyParams();
            return createWithHttpInfo(createDatasetRunItemRequest);
        }

        /**
         * Execute create request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<DatasetRunItem> _callback) throws ApiException {
            CreateDatasetRunItemRequest createDatasetRunItemRequest = buildBodyParams();
            return createAsync(createDatasetRunItemRequest, _callback);
        }
    }

    /**
     * 
     * Create a dataset run item
     * @param createDatasetRunItemRequest  (required)
     * @return CreateRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public CreateRequestBuilder create(String runName, String datasetItemId, String observationId) throws IllegalArgumentException {
        if (runName == null) throw new IllegalArgumentException("\"runName\" is required but got null");
            

        if (datasetItemId == null) throw new IllegalArgumentException("\"datasetItemId\" is required but got null");
            

        if (observationId == null) throw new IllegalArgumentException("\"observationId\" is required but got null");
            

        return new CreateRequestBuilder(runName, datasetItemId, observationId);
    }
}
