/*
 * langfuse
 * ## Authentication  Authenticate with the API using Basic Auth, get API keys in the project settings:  - username: Langfuse Public Key - password: Langfuse Secret Key
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiCallback;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiResponse;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.Pair;
import com.konfigthis.client.ProgressRequestBody;
import com.konfigthis.client.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.konfigthis.client.model.IngestionBatchRequest;
import com.konfigthis.client.model.IngestionResponse;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.ws.rs.core.GenericType;

public class IngestionApiGenerated {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public IngestionApiGenerated() throws IllegalArgumentException {
        this(Configuration.getDefaultApiClient());
    }

    public IngestionApiGenerated(ApiClient apiClient) throws IllegalArgumentException {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    private okhttp3.Call batchCall(IngestionBatchRequest ingestionBatchRequest, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = ingestionBatchRequest;

        // create path and map variables
        String localVarPath = "/api/public/ingestion";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
            "application/json"
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        String[] localVarAuthNames = new String[] { "BasicAuth" };
        return localVarApiClient.buildCall(basePath, localVarPath, "POST", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call batchValidateBeforeCall(IngestionBatchRequest ingestionBatchRequest, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'ingestionBatchRequest' is set
        if (ingestionBatchRequest == null) {
            throw new ApiException("Missing the required parameter 'ingestionBatchRequest' when calling batch(Async)");
        }

        return batchCall(ingestionBatchRequest, _callback);

    }


    private ApiResponse<IngestionResponse> batchWithHttpInfo(IngestionBatchRequest ingestionBatchRequest) throws ApiException {
        okhttp3.Call localVarCall = batchValidateBeforeCall(ingestionBatchRequest, null);
        Type localVarReturnType = new TypeToken<IngestionResponse>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    private okhttp3.Call batchAsync(IngestionBatchRequest ingestionBatchRequest, final ApiCallback<IngestionResponse> _callback) throws ApiException {

        okhttp3.Call localVarCall = batchValidateBeforeCall(ingestionBatchRequest, _callback);
        Type localVarReturnType = new TypeToken<IngestionResponse>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }

    public class BatchRequestBuilder {
        private final List<Object> batch;

        private BatchRequestBuilder(List<Object> batch) {
            this.batch = batch;
        }

        /**
         * Build call for batch
         * @param _callback ApiCallback API callback
         * @return Call to execute
         * @throws ApiException If fail to serialize the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call buildCall(final ApiCallback _callback) throws ApiException {
            IngestionBatchRequest ingestionBatchRequest = buildBodyParams();
            return batchCall(ingestionBatchRequest, _callback);
        }

        private IngestionBatchRequest buildBodyParams() {
            IngestionBatchRequest ingestionBatchRequest = new IngestionBatchRequest();
            ingestionBatchRequest.batch(this.batch);
            return ingestionBatchRequest;
        }

        /**
         * Execute batch request
         * @return IngestionResponse
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public IngestionResponse execute() throws ApiException {
            IngestionBatchRequest ingestionBatchRequest = buildBodyParams();
            ApiResponse<IngestionResponse> localVarResp = batchWithHttpInfo(ingestionBatchRequest);
            return localVarResp.getResponseBody();
        }

        /**
         * Execute batch request with HTTP info returned
         * @return ApiResponse&lt;IngestionResponse&gt;
         * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public ApiResponse<IngestionResponse> executeWithHttpInfo() throws ApiException {
            IngestionBatchRequest ingestionBatchRequest = buildBodyParams();
            return batchWithHttpInfo(ingestionBatchRequest);
        }

        /**
         * Execute batch request (asynchronously)
         * @param _callback The callback to be executed when the API call finishes
         * @return The request call
         * @throws ApiException If fail to process the API call, e.g. serializing the request body object
         * @http.response.details
         <table summary="Response Details" border="1">
            <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
            <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
         </table>
         */
        public okhttp3.Call executeAsync(final ApiCallback<IngestionResponse> _callback) throws ApiException {
            IngestionBatchRequest ingestionBatchRequest = buildBodyParams();
            return batchAsync(ingestionBatchRequest, _callback);
        }
    }

    /**
     * 
     * Batched ingestion for Langfuse Tracing
     * @param ingestionBatchRequest  (required)
     * @return BatchRequestBuilder
     * @http.response.details
     <table summary="Response Details" border="1">
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td>  </td><td>  -  </td></tr>
     </table>
     */
    public BatchRequestBuilder batch(List<Object> batch) throws IllegalArgumentException {
        if (batch == null) throw new IllegalArgumentException("\"batch\" is required but got null");
        return new BatchRequestBuilder(batch);
    }
}
